### ISSUE TITLE
Exporting Accounts.js errors on non-Latin1 characters

### ISSUE THREAD

**Issue by jakcodex** [jakcodex/muledump#257]
```
config.js:1320 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Object.setuptools.app.config.generateAccountsJS (https://jakcodex.github.io/muledump/lib/setuptools/src/config.js:1320:12)
    at Object.setuptools.app.accounts.AccountsJSExport (https://jakcodex.github.io/muledump/lib/setuptools/src/accounts.js:651:48)
    at HTMLDivElement.<anonymous> (https://jakcodex.github.io/muledump/lib/setuptools/src/accounts.js:577:37)
    at HTMLDivElement.dispatch (https://jakcodex.github.io/muledump/vendor/jquery.min.js:2:41772)
    at HTMLDivElement.y.handle (https://jakcodex.github.io/muledump/vendor/jquery.min.js:2:39791)
setuptools.app.config.generateAccountsJS @ config.js:1320
setuptools.app.accounts.AccountsJSExport @ accounts.js:651
(anonymous) @ accounts.js:577
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by jakcodex** [comment]
Archive backups are the answer to this problem.
